version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka1:
    build:
      context: kafka
      args:
        kafka_broker_id: 1
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
    depends_on:
      - zookeeper

  kafka2:
    build:
      context: kafka
      args:
        kafka_broker_id: 1
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
    depends_on:
      - zookeeper

  kafka3:
    build:
      context: kafka
      args:
        kafka_broker_id: 1
    command: /kafka/bin/kafka-server-start.sh /kafka/config/server.properties
    depends_on:
      - zookeeper
